#!/usr/bin/env python

# This is a script to help me find image directories that still need
# keywording. In other words, it will:
#
# Find directories under the current one that:
# - do NOT contain a file named Keywords or Tags
# - DO contain at least one file ending in .jpg or .JPG
# - do NOT contain "web" or "HTML" in the name
# - do not end with a repeated pattern, e.g. images/eclipse/eclipse

import os

def find_nokeywords(topdir):
    '''
       @return: (list of dirs with no tag file,
                 dictionary of dir: list of files not in tag file)
    '''
    dirs_nokw = []
    omitted_files = {}

    for root, dirs, files in os.walk(topdir, topdown=True):
        #print "Checking", root

        # Don't check directories with a path component "html" or "web"
        # They're probably a collection of lower-res images intended
        # to be copied to a website.
        d = root.lower()
        if d.find("/web") > 0 or d.find("/html") > 0 or d.find("/pano") > 0:
            print " ( Skipping", root, ")"
            del dirs[0:]
            continue

        # XXX Need to check for a parent directory with a Tags file
        # that references images in subdirectories. But in that case
        # we also should watch out for subdirectory images that don't
        # appear in the parent's Tags.

        # Don't check directories of the same name as their parent directory.
        # They're probably a collection of lower-res images intended
        # to be copied to a website.
        components = os.path.split(root)
        ultimate = components[-1]
        penultimate = os.path.split(components[-2])[-1]
        if ultimate == penultimate:
            print " ( Skipping", root, ")"
            del dirs[0:]
            continue

        imgfiles = set()

        hasjpeg = False
        haskeywords = False
        for f in files:
            l = f.lower()

            # Don't check directories containing an index.* or showpix.* file
            if l[0:6] == "index." or l[0:8] == "showpix.":
                print " (Skipping", root, ")"
                del dirs[0:]
                hasjpeg = False
                break

            if l.endswith(".jpg"):
                if (not hasjpeg):
                    hasjpeg = True
                imgfiles.add(f)

                # Now I'm using Tags files for gpx track logs as well.
                # Keep the hasjpeg variable name but include gpx.
            elif l.endswith(".gpx"):
                if (not hasjpeg):
                    hasjpeg = True
                imgfiles.add(f)

            if f == "Keywords" or f == "Tags":
                haskeywords = f

        # Done looking through files: if it's not HTML, has at least
        # one jpeg and no keywords file, print it.
        if not hasjpeg:
            continue

        if not haskeywords:
            if root[0:2] == "./":
                dirs_nokw.append(root[2:])
            else:
                dirs_nokw.append(root)
            continue

        # There is a keywords file.
        # Are there any files in the directory that are not mentioned in it?
        kwfiles = set()
        tagfile = os.path.normpath(os.path.join(root, haskeywords))
        with open(tagfile) as kp:
            for line in kp:
                line = line.strip()
                if not line:
                    continue
                if line.startswith("category"):
                    continue
                if ':' not in line:
                    continue
                # Probably a tag line
                for taggedfile in line[line.find(":")+1:].strip().split():
                    kwfiles.add(taggedfile)

        # Now kwfiles is a list of all the files referenced in the Tags file.
        omit = imgfiles - kwfiles
        if omit:
            omitted_files[os.path.normpath(root)] = list(omit)

    return dirs_nokw, omitted_files

dirs_nokw, omitted_files = find_nokeywords('.')
if dirs_nokw:
    print "\nDirectories with no tag file:"
    print '\n'.join(dirs_nokw)

if omitted_files:
    print "\nFiles that don't appear in their directory's tag file:"
    for key in omitted_files:
        print "%s: %s" % (key, ' '.join(omitted_files[key]))
